// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzclfeslxYWJiGJOkfj8WV6LbX3muYQng',
    appId: '1:221208651024:android:ec687bdd1a88746744b195',
    messagingSenderId: '221208651024',
    projectId: 'todo-list-provider-b82c4',
    storageBucket: 'todo-list-provider-b82c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5D4l7r2P7qeiFsv6kuVSWu_l-15jeL90',
    appId: '1:221208651024:ios:bc6204eba67e42d044b195',
    messagingSenderId: '221208651024',
    projectId: 'todo-list-provider-b82c4',
    storageBucket: 'todo-list-provider-b82c4.firebasestorage.app',
    androidClientId: '221208651024-4ee97oqrgfmtpmquffd0cecagrumj78d.apps.googleusercontent.com',
    iosClientId: '221208651024-rso74vv6t9hg4qlok9q1cg4tr253hqsm.apps.googleusercontent.com',
    iosBundleId: 'enzo.crmsolucoes.todoListProvider',
  );

}